// Incarnation Cross Names by Personality Sun Gate
// Based on official Human Design system

export const RIGHT_ANGLE_CROSSES_BY_SUN_GATE: Record<number, string> = {
  1: 'the Sphinx 4',
  2: 'the Sphinx 2',
  3: 'Laws',
  4: 'Explanation 3',
  5: 'Consciousness 4',
  6: 'Eden 3',
  7: 'the Sphinx 3',
  8: 'Contagion 2',
  9: 'Planning 4',
  10: 'Love 4',
  11: 'Eden 4',
  12: 'Eden',
  13: 'the Sphinx',
  14: 'Contagion 3',
  15: 'Love 3',
  16: 'Planning 3',
  17: 'Service 4',
  18: 'Service 3',
  19: 'the Four Ways 4',
  20: 'the Sleeping Phoenix 4',
  21: 'Tension 4',
  22: 'Rulership 4',
  23: 'Explanation 4',
  24: 'the Four Ways 3',
  25: 'the Vessel of Love 4',
  26: 'Confrontation',
  27: 'the Unexpected 3',
  28: 'the Unexpected 4',
  29: 'Contagion 4',
  30: 'Contagion',
  31: 'the Unexpected 2',
  32: 'Maya 4',
  33: 'the Four Ways 2',
  34: 'the Sleeping Phoenix 3',
  35: 'Consciousness 2',
  36: 'Eden 2',
  37: 'Planning 2',
  38: 'Tension 3',
  39: 'Tension 2',
  40: 'Planning',
  41: 'the Unexpected',
  42: 'Maya 3',
  43: 'Explanation 2',
  44: 'the Four Ways',
  45: 'the Vessel of Love 3',
  46: 'the Vessel of Love 2',
  47: 'Rulership 3',
  48: 'Rulership 2',
  49: 'Explanation',
  50: 'Maya 2',
  51: 'Penetration',
  52: 'Service 2',
  53: 'Penetration 2',
  54: 'Penetration 3',
  55: 'Rulership',
  56: 'Distraction',
  57: 'Penetration 4',
  58: 'Service',
  59: 'the Sleeping Phoenix 2',
  60: 'Laws 2',
  61: 'Maya',
  62: 'Consciousness',
  63: 'Consciousness 3',
  64: 'Consciousness 3'
};

export const JUXTAPOSITION_CROSSES_BY_SUN_GATE: Record<number, string> = {
  1: 'Self-Expression',
  2: 'the Driver',
  3: 'Mutation',
  4: 'Formulization',
  5: 'Habits',
  6: 'Conflict',
  7: 'Interaction',
  8: 'Contribution',
  9: 'Focus',
  10: 'Behavior',
  11: 'Ideas',
  12: 'Articulation',
  13: 'the Listener',
  14: 'Power Skills',
  15: 'Extremes',
  16: 'Experimentation',
  17: 'Opinion',
  18: 'Correction',
  19: 'Need',
  20: 'the Now',
  21: 'Control',
  22: 'Grace',
  23: 'Assimilation',
  24: 'Rationalization',
  25: 'Innocence',
  26: 'the Trickster',
  27: 'Caring',
  28: 'Risks',
  29: 'Commitment',
  30: 'Fates',
  31: 'Leading',
  32: 'Conservation',
  33: 'Retreat',
  34: 'Power',
  35: 'Experience',
  36: 'Crisis',
  37: 'Friendship',
  38: 'Opposition',
  39: 'Provocation',
  40: 'Denial',
  41: 'Fantasy',
  42: 'Completion',
  43: 'Insight',
  44: 'Alertness',
  45: 'Possession',
  46: 'Determination',
  47: 'Oppression',
  48: 'Depth',
  49: 'Principles',
  50: 'Values',
  51: 'Shock',
  52: 'Stillness',
  53: 'Beginnings',
  54: 'Ambition',
  55: 'Moods',
  56: 'Stimulation',
  57: 'Intuition',
  58: 'Vitality',
  59: 'Strategy',
  60: 'Limitation',
  61: 'Mystery',
  62: 'Detail',
  63: 'Doubts',
  64: 'Confusion'
};

export const LEFT_ANGLE_CROSSES_BY_SUN_GATE: Record<number, string> = {
  1: 'Defiance 2',
  2: 'Defiance',
  3: 'Wishes',
  4: 'Revolution 2',
  5: 'Separation 2',
  6: 'Distraction 2',
  7: 'Masks',
  8: 'Upheaval',
  9: 'Dedication 2',
  10: 'Prevention 2',
  11: 'Education 2',
  12: 'Education',
  13: 'Masks 2',
  14: 'Upheaval 2',
  15: 'Prevention',
  16: 'Dedication',
  17: 'Upheaval 3',
  18: 'Upheaval 4',
  19: 'Refinement',
  20: 'Duality 2',
  21: 'Endeavor 2',
  22: 'Dominion',
  23: 'Dedication 3',
  24: 'Incarnation',
  25: 'Healing 2',
  26: 'Confrontation',
  27: 'Alignment 2',
  28: 'Alignment',
  29: 'Industry 2',
  30: 'Industry',
  31: 'Alpha',
  32: 'Limitations',
  33: 'Refinement 2',
  34: 'Duality',
  35: 'Separation',
  36: 'Distraction 3',
  37: 'Migration',
  38: 'Individualism',
  39: 'Individualism 2',
  40: 'Migration 2',
  41: 'Alpha 2',
  42: 'Limitations 2',
  43: 'Dedication 4',
  44: 'Incarnation 2',
  45: 'Healing',
  46: 'Healing 3',
  47: 'Informing',
  48: 'Endeavor',
  49: 'Revolution',
  50: 'Wishes 2',
  51: 'the Clarion 2',
  52: 'Demands',
  53: 'Cycles',
  54: 'Cycles 2',
  55: 'Informing 2',
  56: 'Distraction 4',
  57: 'the Clarion',
  58: 'Demands 2',
  59: 'the Alpha 3',
  60: 'Dedication 5',
  61: 'Obscuration',
  62: 'Obscuration 2',
  63: 'Completion',
  64: 'Dominion 2'
};

// Calculate the proper incarnation cross name based on gates and lines
export function getIncarnationCrossName(
  personalitySunGate: number,
  personalitySunLine: number,
  designSunLine: number
): string {
  // Determine cross type based on the Sun line positions
  // This follows the official Human Design logic from the Ruby implementation
  if (personalitySunLine < 5 && designSunLine >= 3) {
    // Right Angle Cross
    const crossName = RIGHT_ANGLE_CROSSES_BY_SUN_GATE[personalitySunGate];
    return crossName ? `Right Angle Cross of ${crossName}` : `Right Angle Cross of Gate ${personalitySunGate}`;
  } else if (personalitySunLine >= 5) {
    // Left Angle Cross
    const crossName = LEFT_ANGLE_CROSSES_BY_SUN_GATE[personalitySunGate];
    return crossName ? `Left Angle Cross of ${crossName}` : `Left Angle Cross of Gate ${personalitySunGate}`;
  } else {
    // Juxtaposition Cross
    const crossName = JUXTAPOSITION_CROSSES_BY_SUN_GATE[personalitySunGate];
    return crossName ? `Juxtaposition Cross of ${crossName}` : `Juxtaposition Cross of Gate ${personalitySunGate}`;
  }
}